# Generated by Django 2.2.16 on 2022-07-10 14:42

from django.db import migrations, models
import django.db.models.deletion
import equipment.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название оборудования')),
                ('sn_mask', models.CharField(help_text='N:0-9, A:A-Z, a:a-z, X:0-Z, Z:-,_,@', max_length=10, validators=[equipment.validators.validate_sn_mask], verbose_name='Маска серийного номера')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10, verbose_name='Серийный номер')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Метка удаления')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipment.EquipmentType', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'unique_together': {('equipment_type', 'serial_number')},
            },
        ),
    ]
